version: '3.7'

services:
  team-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./src:/teamproject/src
    ports:
      - 3000:3000

  team-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'teamdatabase'
    ports:
      - 3306:3306
